server:
  port: 8084

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ecommerce  ?createDatabaseIfNotExist=true
    username: root
    password: Billionaire1.
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update